### ISSUE TITLE
Don't understand the usage

### ISSUE THREAD

**Issue by Vagrantin** [wpup/wp-cli-media-restore#5]
Hello, 
First thanks for creating this extension !
I'm trying to use it to restore my images to my Wordpress but I think I'm doing it all wrong:

1) I navigate to the folder where I have all my images I want to restore, this folder is on the same server where my WP is hosted.

2)  Then launch ,
`wp media restore --uploads-url=http://mywordpress.com/blog/wp-content/uploads/`
the _**uploads**_ folder is the one where I want to push my restored images.
3) It runs until 100% then for all ID's I got 

> Warning: Could not retrieve remote file for attachment ID xxx, HTTP response code 404

Hope this is clear enough,
Any details on what I'm doing wrong would be very helpful ! Thanks !

With kind regards
Matth

**Comment by frozzare** [comment]
Thanks!

The cli command will get all attachment ids from the database and try to download all files via http. If a id exists in the database and not as a file it will not find any and that's why you get 404 for some images. It's not a problem with this cli command. It just means that something exists in the database but not on the filesystem, maybe the file was deleted but not deleted in the database.
